host: 0.0.0.0
port: 8080

title: Stephen Pearce
description: Stephen Pearce's homepage. Featuring games, retrospectives and a blog.

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore: [
    pre
  ]
  envs: []
  blanklines: false
  profile: false
  startings: []