host: 0.0.0.0
port: 8080
url: https://stevepdp.dev
title: Stephen Pearce
description: Stephen Pearce's homepage. Featuring games, devlogs and retrospectives.

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore: [
    pre
  ]
  envs: []
  blanklines: false
  profile: false
  startings: []